spring:
  application:
    name: deal
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_bank_DB
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: 8082