spring:
  application:
    name: dossier
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
  mail:
    username: puchokok2001@gmail.com
    password: ???? ???? ???? ????
server:
  port: 8083