spring:
  application:
    name: dossier
  mail:
    host: smtp.gmail.com
    port: 587
    username: CreditBank
    password: admin
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8083