name: CI Pipeline

on:
  push:
    branches:
      - develop
      - feature/DevOps
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Test Projects
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project-path:
          - calculator
          - deal
          - statement
          - gateway

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Test with Maven
        run: mvn -f ${{ matrix.project-path }}/pom.xml clean verify

      - name: Generate Code Coverage Report (JaCoCo)
        run: mvn -f ${{ matrix.project-path }}/pom.xml jacoco:report

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ${{ matrix.project-path }}/target/site/jacoco/jacoco.xml
          flags: ${{ matrix.project-path }}
          name: ${{ matrix.project-path }}
          fail_ci_if_error: true

      - name: Run SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=FistMr_credit-bank